
FROM biocontainers/biocontainers:latest

MAINTAINER Rui Luis <ruisergioluis@gmail.com>

ENV SALMON_VERSION 0.8.1
ENV KALLISTO_VERSION 0.45

RUN conda install -c bioconda salmon kallisto

WORKDIR /data/
